### ISSUE TITLE
Excracting edited rom

### ISSUE THREAD

**Issue by pissopasso** [NielsHotweels/InazumaDSEditor#1]
Im sorry but whenever i click on "save rom" nothing happens, the original file doesnt change and it only saves what did on the editor. how do i actually get the edited rom out?

**Comment by NielsHotweels** [comment]
The changes are made to the rom you opened, it does not create a new rom.

**Comment by pissopasso** [comment]
but the rom stayed the same, the last date of modification of the file is the same as when it was downloaded

**Comment by NielsHotweels** [comment]
have you tested the changes ingame?

Op di 27 aug 2024 om 18:04 schreef pissopasso ***@***.***>:
